name: Caching with npm
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache release version 
        id: cache-version
        uses: actions/cache@v3
        env:
          cache-name: cache-release-version
        with:
          path: ~/version_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/release-version.txt') }}

      # create a caching dir (if not exists)
      - if: ${{ steps.cache-version.outputs.cache-hit != 'true' }}
        name: Create cache dir 
        run: mkdir ~/version_cache
        shell: bash

      # assign cache version to an environment variable

      # run python script to retrieve latest version 
      # and compare to latest cached version (in env var)
      - name: Read cached version
        run: cat ~/version_cache/release-version.txt
        shell: bash




