name: demo 
on: push

jobs:
  version-num:
    runs-on: ubuntu-latest
    name: version-lasest 
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
        run: ./demo.py
