name: demo

on: 
  push:
    branches:
      - "demo"

jobs:
  recall-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: 3.9.12

    - uses: actions/cache@v3
      with:
        path: src 
        key: "${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('version_last.txt') }}"
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-build
          ${{ runner.os }}
    - name: demo 
      run: python src/cache_read.py


  clear-cache:
      runs-on: ubuntu-latest
      steps:
        - name: Clear cache
          uses: actions/github-script@v6
          with:
            script: |
              console.log("About to clear")
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              for (const cache of caches.data.actions_caches) {
                console.log(cache)
                github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
              }
              console.log("Clear completed")
  write-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: 3.9.12
    - name: demo 
      run: python src/cache_write.py
