name: demo 
on:
  push:
    branches:
      - demo 

jobs:
  version-num:
    runs-on: ubuntu-latest
    name: version-lasest 
    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: demo 
        run: /demo.py
