name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  call-workflow-1:
    uses: rpappalax/testapp2/.github/workflow-templates/demo.yml@main

